server:
  servlet:
    context-path: /auth
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/auth
    username: lijian
    password: lijian
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 1

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false
logging.level.org.springframework: debug